### ISSUE TITLE
1.21.4 Paper Hard fork v50: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Foundation#342]
Updated my plugin to Foundation 6.9.13 and tested my plugin on paper 1.21.3 no issues.

Updated server to newest paper release 1.21.4, which is now the hard fork version of paper, and encountered the following error:

[06:33:42] [Server thread/INFO]: Cobrex_III issued server command: /tm
[06:33:42] [Server thread/ERROR]: TownyMenu 1.8.11 encountered an ExceptionInInitializerError! Please check your error.log and report this issue with the information in that file. Running Paper 1.21.4-R0.1-SNAPSHOT and Java 21.0.3
[06:33:42] [Server thread/INFO]: java.lang.ExceptionInInitializerError
[06:33:42] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.townymenu.town.command.TownMenuCommand.onCommand(TownMenuCommand.java:35)
[06:33:42] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:406)
[06:33:42] [Server thread/INFO]: 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82)
[06:33:42] [Server thread/INFO]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[06:33:42] [Server thread/INFO]: java.lang.NullPointerException: sound is marked non-null but is null
[06:33:42] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.model.SimpleSound.<init>(SimpleSound.java:19)
[06:33:42] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.model.SimpleSound.<init>(SimpleSound.java:66)
[06:33:42] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.menu.Menu.<clinit>(Menu.java:79)
[06:33:42] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.townymenu.town.command.TownMenuCommand.onCommand(TownMenuCommand.java:35)
[06:33:42] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:406)
[06:33:42] [Server thread/INFO]: 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82)
[06:33:42] [Server thread/INFO]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[06:33:42] [Server thread/INFO]: [TownyMenu] !-----------------------------------------------------!
[06:33:42] [Server thread/INFO]: [TownyMenu]  Failed to execute command /townmenu 
[06:33:42] [Server thread/INFO]: [TownyMenu] !-----------------------------------------------------!
[06:33:42] [Server thread/INFO]: [TownyMenu 1.8.11] Command /townmenu took 116.02 ms

Thanks

**Comment by Ultimating** [comment]
To add, one of my users also reported a very similar error to this with one of my plugins built with Foundation.

[Stacktrace](https://pastebin.com/GG1BycQQ)

**Comment by kangarko** [comment]
Sound names have changed. Check that the Sound you are putting in the SimpleSound constructor below exists:

```java
public SimpleSound(Sound sound, float volume) {
		this(sound, volume, 1.0F, true, true);
	}
```

If unsure ZIP me your entire source code and I can have a look when I have more time. Thanks.

**Comment by cobrex1** [comment]
Morning Matej, I have not used SimpleSounds in my project as far as I know (well not directly). I will email my ziped project if you like.

**Comment by kangarko** [comment]
Should be fixed in the new Foundation 6 release!

**Comment by cobrex1** [comment]
This update has not fixed the issue. I have used Foundation 6 6.9.15.

Here is the error:
[16:50:56] [Server thread/ERROR]: TownyMenu 1.8.11 encountered an ExceptionInInitializerError! Please check your error.log and report this issue with the information in that file. Running Paper 1.21.4-R0.1-SNAPSHOT and Java 21.0.3
[16:50:56] [Server thread/INFO]: java.lang.ExceptionInInitializerError
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.menu.Menu.<clinit>(Menu.java:79)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.townymenu.town.command.TownMenuCommand.onCommand(TownMenuCommand.java:35)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:406)
[16:50:56] [Server thread/INFO]: 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82)
[16:50:56] [Server thread/INFO]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[16:50:56] [Server thread/INFO]: me.cobrex.TownyMenu.lib.fo.exception.FoException: Report: Method interface org.bukkit.Sound.valueOf(AMBIENT_BASALT_DELTAS_ADDITIONS) not found!
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.Valid.checkNotNull(Valid.java:60)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.ReflectionUtil.invokeStatic(ReflectionUtil.java:434)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.ReflectionUtil.lookupEnumSilent(ReflectionUtil.java:902)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.remain.CompSound.<init>(CompSound.java:1724)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.remain.CompSound.<clinit>(CompSound.java:40)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.menu.Menu.<clinit>(Menu.java:79)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.townymenu.town.command.TownMenuCommand.onCommand(TownMenuCommand.java:35)
[16:50:56] [Server thread/INFO]: 	at TownyMenu-1.8.11.jar//me.cobrex.TownyMenu.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:406)
[16:50:56] [Server thread/INFO]: 	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82)
[16:50:56] [Server thread/INFO]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[16:50:56] [Server thread/INFO]: [TownyMenu] !-----------------------------------------------------!
[16:50:56] [Server thread/INFO]: [TownyMenu]  Failed to execute command /townmenu 
[16:50:56] [Server thread/INFO]: [TownyMenu] !-----------------------------------------------------!
[16:50:56] [Server thread/INFO]: [TownyMenu 1.8.11] Command /townmenu took 149.09 ms

**Comment by cobrex1** [comment]
just to add to this here is the line that is causing the issue:

new TownMenu(town, getPlayer()).displayTo(getPlayer());

I think it is the displayTo(getPlayer())

**Comment by cobrex1** [comment]
I am also getting this error on disconnect even though I don't have the menu open
[latestlog.txt](https://github.com/user-attachments/files/18322352/latestlog.txt)

**Comment by kangarko** [comment]
Will continue via email, apologizes for the broken fix
